steps:
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ['test', 'assemble']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/v-image', '--build-arg=JAR_FILE=build/libs/playground-0.0.1.jar', '.']
options:
  logStreamingOption: STREAM_ON
images: ['gcr.io/$PROJECT_ID/v-image']
tags: [${TAG1}, ${TAG2}]
artifacts:
  objects:
    location: "gs://gcb-playgound"
    paths:
      - "build/libs/playground-0.0.1.jar"
