steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=secret-name > /root/.ssh/id_github' ]
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # Set up git with key and domain
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 600 /root/.ssh/id_github
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_github
        EOF
        eval `ssh-agent`
        ssh-add /root/.ssh/id_github
        cat /root/.ssh/id_github.pub >> /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # Connect to the repository
  - name: 'gcr.io/cloud-builders/git'
    args:
      - clone
      - git@github.com:git-username/git-repository
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ['test', 'assemble']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/v-image', '--build-arg=JAR_FILE=build/libs/playground-0.0.1.jar', '.']
options:
  logStreamingOption: STREAM_ON
images: ['gcr.io/$PROJECT_ID/v-image']